#!/usr/bin/env python3
"""Build the reader pages from the single maintained formula source.

Only Python's standard library is required. This renders documentation; it
never changes a numerical formula kernel or its representative convention.
"""
import argparse
from hashlib import sha256
import json
from pathlib import Path
import re
import sys

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SOURCE = HERE / 'source'
CATALOG = SOURCE / 'catalog.json'
TOKEN = re.compile(r'\{\{(equation|include):([A-Za-z0-9_./-]+)\}\}')
MATH = re.compile(r'```math\n(.*?)\n```', re.S)


def shares_equations(target):
    # Coefficient appendices are already explicit views of fixed coefficient
    # data. Keep their long row lists together, rather than making each row
    # a separate editable formula file.
    stem = Path(target).stem
    return not any(part in stem for part in
                   ('COEFFICIENT', 'WORD', '_FACES', '_LIFT_', '_LIFTS',
                    '_BINARY_', '_TENSOR_', '_PHYSICAL_'))


def digest(text):
    return sha256(text.encode()).hexdigest()


def source_path(name):
    path = (SOURCE / name).resolve()
    if SOURCE.resolve() not in path.parents:
        raise ValueError('Source path escapes the maintained directory')
    return path


def render_source(name, used, chain=()):
    if name in chain:
        raise ValueError('Include cycle: ' + ' -> '.join(chain + (name,)))
    path = source_path(name)
    text = path.read_text()
    used[name] = digest(text)
    def replace(match):
        kind, target = match.groups()
        if kind == 'equation':
            target = 'equations/' + target + '.tex'
            equation = source_path(target).read_text().rstrip('\n')
            used[target] = digest(source_path(target).read_text())
            return '```math\n' + equation + '\n```'
        return render_source(target, used, chain + (name,))
    return TOKEN.sub(replace, text)


def output_path(entry):
    if (ROOT / 'publication/formula_reference').is_dir() and entry.get('private_output'):
        return ROOT / entry['private_output']
    return ROOT / entry['output']


def import_page(target, incoming):
    catalog = json.loads(CATALOG.read_text()) if CATALOG.exists() else {'pages': []}
    matches = [entry for entry in catalog['pages'] if entry['output'] == target]
    if matches:
        entry = matches[0]
    else:
        stem = Path(target).name
        entry = {'output': target, 'source': 'pages/' + stem}
        if any(x['source'] == entry['source'] for x in catalog['pages']):
            raise ValueError('Duplicate page basename: ' + stem)
        catalog['pages'].append(entry)
    existing = {p.read_text().rstrip('\n'): p.stem for p in (SOURCE / 'equations').glob('*.tex')}
    text = incoming.read_text()
    text = re.sub(r'^<!-- Generated by build_reference.py;.*?-->\n\n', '', text, count=1)
    prefix = Path(target).stem.lower().replace('_', '-')
    counter = 0
    def replace(match):
        nonlocal counter
        equation = match.group(1).rstrip('\n')
        if equation not in existing:
            heading = re.findall(r'^#{1,6}\s+(.+)$', text[:match.start()], re.M)
            label = re.sub(r'[^a-z0-9]+', '-', heading[-1].lower()).strip('-')[:52] if heading else 'equation'
            while True:
                counter += 1
                key = '{}--{}--{}'.format(prefix, label, counter)
                path = SOURCE / 'equations' / (key + '.tex')
                if not path.exists(): break
            path.write_text(equation + '\n')
            existing[equation] = key
        return '{{equation:' + existing[equation] + '}}'
    source_path(entry['source']).write_text(MATH.sub(replace, text) if shares_equations(target) else text)
    catalog['pages'].sort(key=lambda x: x['output'])
    CATALOG.write_text(json.dumps(catalog, indent=2) + '\n')


def build(check=False):
    catalog = json.loads(CATALOG.read_text())
    manifest = {'format': 1, 'maintained_source': 'source/', 'pages': [], 'equations': {}}
    changed = []
    for entry in catalog['pages']:
        used = {}
        body = render_source(entry['source'], used)
        text = '<!-- Generated by build_reference.py; edit source/{} instead. -->\n\n'.format(entry['source']) + body
        target = output_path(entry)
        if not target.exists() or target.read_text() != text:
            changed.append(entry['output'])
            if not check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(text)
        manifest['pages'].append({'output': entry['output'], 'source': entry['source'], 'sha256': digest(text), 'dependencies': used})
        for name, checksum in used.items():
            if name.startswith('equations/'):
                item = manifest['equations'].setdefault(name, {'sha256': checksum, 'used_by': []})
                item['used_by'].append(entry['output'])
    payload = json.dumps(manifest, indent=2) + '\n'
    path = HERE / 'REFERENCE_MANIFEST.json'
    if not path.exists() or path.read_text() != payload:
        changed.append('docs/formulas/REFERENCE_MANIFEST.json')
        if not check: path.write_text(payload)
    summary = {'status': 'FAIL' if check and changed else 'PASS', 'pages': len(catalog['pages']),
               'unique_display_equations': len(manifest['equations']),
               'shared_equations': sum(len(v['used_by']) > 1 for v in manifest['equations'].values()),
               'changed': changed}
    print(json.dumps(summary))
    return not (check and changed)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if a generated page differs from its maintained source')
    parser.add_argument('--import-page', help='Repository-relative output path for a reviewed new/revised page')
    parser.add_argument('--from-file', type=Path, help='Reviewed Markdown to import into the maintained source')
    args = parser.parse_args()
    if bool(args.import_page) != bool(args.from_file): parser.error('Use --import-page and --from-file together')
    if args.import_page:
        if args.check: parser.error('Import and --check are separate steps')
        import_page(args.import_page, args.from_file)
    return 0 if build(args.check) else 1


if __name__ == '__main__': sys.exit(main())
