if not IsBound(AFS_ROOT) then AFS_ROOT:="/home/user/xyren/AllFSPT";fi;
Read(Concatenation(AFS_ROOT,"/gap/backend.g"));;
Read(Concatenation(AFS_ROOT,"/gap/backend_mod2_contraction.g"));;
Read(Concatenation(AFS_ROOT,"/gap/backend_bar_mod2.g"));;
Read(Concatenation(AFS_ROOT,"/gap/formula_data.g"));;
Read(Concatenation(AFS_ROOT,"/gap/formulas.g"));;
Read(Concatenation(AFS_ROOT,"/gap/formula_fast.g"));;
Read(Concatenation(AFS_ROOT,"/gap/stacking_closed_cf.g"));;
if not IsBound(AFS_SG) then AFS_SG:=219;fi;
c:=AFSBackend(AFS_SG);;H:=AFSCohomology(c,3,"F2");;
if Length(H.generators)=0 then Error("benchmark needs H3 generator");fi;
if not IsBound(AFS_BASIS_INDEX) then AFS_BASIS_INDEX:=1;fi;
v:=H.generators[AFS_BASIS_INDEX];;
if ForAny(v*AFSDifferential(c,3,"F2"),x->x mod 2<>0) then Error("CF input must be closed");fi;
cb:=AFSBarMod2(c,3,v);;ob:=AFSClosedCFObstruction(cb);;
oldcb:=AFSBar(c,3,"F2",v);;oldob:=AFSFormula("obstruction",c,rec(p:=2,a:=AFSZero,c:=oldcb));;
gs:=GeneratorsOfGroup(c.G);;elts:=Concatenation(gs,List(gs,g->g^-1),[gs[1]^2,gs[1]*gs[Length(gs)],gs[Length(gs)]^-2]);;
for j in [1..24] do
  xs:=List([1..5],i->elts[1+((3*j+i^2) mod Length(elts))]);;
  if CallFuncList(ob,xs)<>CallFuncList(oldob,xs) then Error("closed CF translated pointwise comparison");fi;
od;
Print("CLOSED_CF_POINTWISE_PASS sg=",AFS_SG," cases=24\n");
t:=Runtime();;nv:=AFSNative(c,5,"U1s",ob);;
Print("CLOSED_CF_MOD2_NATIVE sg=",AFS_SG," cpu_ms=",Runtime()-t," vector=",nv,"\n");
t:=Runtime();;iv:=AFSNative(c,5,"U1s",oldob);;
Print("GENERAL_CF_INTEGRAL_NATIVE sg=",AFS_SG," cpu_ms=",Runtime()-t," vector=",iv,"\n");
if nv<>iv then Error("closed CF versus general full native phase vectors differ");fi;
Print("AFS_CLOSED_CF_NATIVE_PASS sg=",AFS_SG,"\n");
QUIT_GAP(0);
