AFS_ROOT:=".";;
OnBreak:=function() Where(25);QUIT_GAP(1);end;;
Read("gap/backend.g");;
Read("gap/backend_diagonal.g");;
Read("gap/formula_data.g");;
Read("gap/pip_o5_program.g");;
Read("gap/formulas.g");;
Read("gap/classification.g");;
Read("gap/pip.g");;
Read("gap/stacking.g");;
sg:=Int(GAPInfo.SystemEnvironment.AFS_TEST_SG);;
ctx:=AFSBackend(sg);;
C:=AFSClassify(ctx);;
Assert(0,Length(C.mcFinalBasis)=0);
native:=AFSStackCFOnly(C);;
Print("NATIVE_CF_RESULT ",sg," ",native.invariants," ",native.presentation,"\n");
model:=AFSStackFromClassification(C);;
full:=AFSStackClassification(model);;
Assert(0,native.status="computed" and full.status="computed");
Assert(0,native.invariants=full.invariants);
Print("NATIVE_CF_FULL_COMPARISON_PASS ",sg," ",full.invariants,"\n");
Print("FULL_PRESENTATION ",full.presentation,"\n");
QUIT_GAP(0);
