AFS_ROOT:=".";;
OnBreak:=function() Where(25);QUIT_GAP(1);end;;
Read("gap/backend.g");;
Read("gap/backend_diagonal.g");;
Read("gap/formula_data.g");;
Read("gap/formula_fast.g");;
Read("gap/pip_o5_program.g");;
Read("gap/pip_o5_sign.g");;
Read("gap/formulas.g");;
Read("gap/classification.g");;
Read("gap/pip.g");;
Read("gap/stacking.g");;
Read("gap/pip_coordinate_data.g");;
Read("gap/pip_coordinates.g");;
Read("gap/pip_diagonal_data.g");;
Read("gap/pip_c4_data.g");;
Read("gap/pip_stacking.g");;
sg:=Int(GAPInfo.SystemEnvironment.AFS_TEST_SG);;
ctx:=AFSBackend(sg);;
C:=AFSClassify(ctx);;
result:=AFSExplicitPipStacking(C);;
Print("EXPLICIT_PIP_STACKING_RESULT ",sg," ",result.status,"\n");
Assert(0,result.status="computed");
Assert(0,result.fullUpperPhaseWitness=true);
Print("EXPLICIT_PIP_STACKING_INVARIANTS ",sg," ",result.invariants,"\n");
Print("EXPLICIT_PIP_STACKING_PRESENTATION ",sg," ",result.fullPresentation,"\n");
LoadPackage("json");;
serialized:=GapToJsonString(AFSExplicitPipExport(C,result));;
Assert(0,Length(serialized)>0);
Print("EXPLICIT_PIP_STACKING_JSON_BYTES ",Length(serialized),"\n");
Print("EXPLICIT_PIP_STACKING_TEST_PASS ",sg,"\n");
QUIT_GAP(0);
