AFS_ROOT:=".";;
OnBreak:=function() Where(25);QUIT_GAP(1);end;;
Read("gap/backend.g");;
Read("gap/backend_diagonal.g");;
Read("gap/formula_data.g");;
Read("gap/formula_fast.g");;
Read("gap/pip_o5_program.g");;
Read("gap/pip_o5_sign.g");;
Read("gap/formulas.g");;
Read("gap/classification.g");;
Read("gap/pip.g");;
Read("gap/stacking.g");;
Read("gap/pip_coordinate_data.g");;
Read("gap/pip_coordinates.g");;
Read("gap/pip_diagonal_data.g");;
Read("gap/pip_c4_data.g");;
Read("gap/pip_stacking.g");;
ctx:=AFSBackend(7);;
lift:=AFSPipC4FlatLift(rec(ctx:=ctx));;
Assert(0,lift<>fail and lift.status="computed");;
x:=lift.state;;
tbar:=AFSBar(ctx,1,"Z",x.C4PullbackCertificate.nativeCharacter1);;
t:=AFSMemo(function(g) return tbar(g) mod 4;end);;
dt:=AFSCoboundary(ctx,"Z",t);;
Assert(0,AFSStackSupportZero(ctx,1,2,function(g) return t(g)+ctx.s(g);end));
Assert(0,AFSStackSupportZero(ctx,2,0,function(g,h) return dt(g,h) mod 4;end));
Q:=AFSFormula("pip_parity",ctx,rec(p:=1,n:=x.n,b:=x.b));;
Assert(0,AFSStackSupportZero(ctx,4,2,AFSCoadd(2,[Q,AFSCoboundary(ctx,"F2",x.c)])));
O5:=AFSFormula("pip_obstruction",ctx,rec(p:=1,n:=x.n,b:=x.b,c:=x.c));;
Assert(0,AFSStackSupportZero(ctx,5,1,AFSCoadd(1,[AFSCoboundary(ctx,"U1s",x.v),AFSComul(1,-1,O5)])));
Print("ACTUAL_C4_HOMOMORPHISM_AND_FULL_FLAT_PULLBACK_PASS SG7\n");
QUIT_GAP(0);
