AFS_ROOT:=".";;
OnBreak:=function() Where(25);QUIT_GAP(1);end;;
Read("gap/backend.g");;
Read("gap/backend_diagonal.g");;
Read("gap/formula_data.g");;
Read("gap/formula_fast.g");;
Read("gap/pip_o5_program.g");;
Read("gap/formulas.g");;
Read("gap/classification.g");;
Read("gap/pip.g");;
Read("gap/stacking.g");;
ctx:=AFSBackend(11);;C:=AFSClassify(ctx);;
lower:=AFSStackCFOnly(C);;
x:=AFSReconstructNativeCFLift(ctx,lower.generators[2]);;
Assert(0,AFSStackCheckFlat(ctx,x));
doubled:=AFSStackPower(ctx,x,2);;
co:=C.H4U.coordinates(AFSNative(ctx,4,"U1s",doubled.v));;
Assert(0,C.bosQuotient.project(co)=[1]);
Print("NATIVE_CF_MARKED_RECONSTRUCTION_PASS SG11 nonzero bosonic carry\n");
QUIT_GAP(0);
