AFS_ROOT:=".";;
OnBreak:=function() Where(25);QUIT_GAP(1);end;;
Read("gap/backend.g");;
Read("gap/backend_diagonal.g");;
Read("gap/formula_data.g");;
Read("gap/formula_fast.g");;
Read("gap/pip_o5_program.g");;
Read("gap/pip_o5_sign.g");;
Read("gap/formulas.g");;
Read("gap/classification.g");;
Read("gap/pip.g");;
Read("gap/stacking.g");;
Read("gap/pip_coordinate_data.g");;
Read("gap/pip_coordinates.g");;
Read("gap/pip_diagonal_data.g");;
Read("gap/pip_c4_data.g");;
Read("gap/pip_stacking.g");;
sg:=Int(GAPInfo.SystemEnvironment.AFS_TEST_SG);;
ctx:=AFSBackend(sg);;
C:=AFSClassify(ctx);;
model:=AFSStackFromClassification(C);;
lower:=AFSStackClassification(model);;
fastLift:=AFSStackPipLift(C);;
fastSquare:=AFSStackPipSquare(ctx,fastLift.state);;
fastReduction:=AFSStackReduce(model,fastSquare.target,true);;
Print("C4_SAME_BASIS_FAST_RELATION ",fastReduction.coordinates,"\n");
AFS_PIP_USE_C4:=false;;
genericLift:=AFSStackPipLift(C);;
genericSquare:=AFSStackPipSquare(ctx,genericLift.state);;
genericReduction:=AFSStackReduce(model,genericSquare.target,true);;
Print("C4_SAME_BASIS_GENERIC_RELATION ",genericReduction.coordinates,"\n");
difference:=genericReduction.coordinates-fastReduction.coordinates;;
while Length(difference)<Length(lower.generators) do Add(difference,0);od;
solve:=AFSStackLatticeSolver(Concatenation(lower.presentation,2*IdentityMat(Length(lower.generators))),Length(lower.generators));;
Assert(0,solve(difference)<>fail);
if ForAll(lower.invariants,x->x=2) then Assert(0,genericReduction.coordinates=fastReduction.coordinates);fi;
Print("C4_VS_GENERIC_SAME_MARKED_LOWER_BASIS_PASS ",sg,"\n");
QUIT_GAP(0);
