"""Independent faithful 3D geometry fingerprints for the 32 point groups.

All matrices below are explicit geometric generators, not copied spectra from
computed results. Cartesian axes are used except in the hexagonal plane,
whose basis is e1=(1,0), e2=(1/2,sqrt(3)/2). No classification data enter here.
"""
from collections import Counter
from functools import lru_cache


def _diag(x, y, z):
    return ((x, 0, 0), (0, y, 0), (0, 0, z))


def _mul(a, b):
    return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(3))
                       for j in range(3)) for i in range(3))


def _det(a):
    return (a[0][0]*(a[1][1]*a[2][2]-a[1][2]*a[2][1])
            - a[0][1]*(a[1][0]*a[2][2]-a[1][2]*a[2][0])
            + a[0][2]*(a[1][0]*a[2][1]-a[1][1]*a[2][0]))


IDENTITY = _diag(1, 1, 1)
INVERSION = _diag(-1, -1, -1)
HORIZONTAL_MIRROR = _diag(1, 1, -1)
VERTICAL_MIRROR = _diag(1, -1, 1)
HALF_TURN_X = _diag(1, -1, -1)
HALF_TURN_Z = _diag(-1, -1, 1)
QUARTER_TURN_Z = ((0, -1, 0), (1, 0, 0), (0, 0, 1))
# In the hexagonal basis: a 60-degree proper rotation and reflection in e1.
SIXTH_TURN_Z = ((0, -1, 0), (1, 1, 0), (0, 0, 1))
HEX_VERTICAL_MIRROR = ((1, 1, 0), (0, -1, 0), (0, 0, 1))
THIRD_TURN_Z = _mul(SIXTH_TURN_Z, SIXTH_TURN_Z)
HEX_HALF_TURN_X = _mul(HEX_VERTICAL_MIRROR, HORIZONTAL_MIRROR)
ROTOREFLECTION_4 = _mul(QUARTER_TURN_Z, HORIZONTAL_MIRROR)
# Cartesian threefold rotation about (1,1,1), and the x=y reflection.
AXIS_CYCLE = ((0, 0, 1), (1, 0, 0), (0, 1, 0))
SWAP_XY = ((0, 1, 0), (1, 0, 0), (0, 0, 1))


# (HM, abstract order, explicit faithful matrix generators).
# T is generated by two-coordinate sign flips and an even axis permutation.
# Td additionally has odd axis permutations; O instead contains proper C4.
CATALOGUE = (
    ('1', 1, ()),
    ('-1', 2, (INVERSION,)),
    ('2', 2, (HALF_TURN_Z,)),
    ('m', 2, (HORIZONTAL_MIRROR,)),
    ('2/m', 4, (HALF_TURN_Z, HORIZONTAL_MIRROR)),
    ('222', 4, (HALF_TURN_Z, HALF_TURN_X)),
    ('mm2', 4, (HALF_TURN_Z, VERTICAL_MIRROR)),
    ('mmm', 8, (HALF_TURN_Z, HALF_TURN_X, INVERSION)),
    ('4', 4, (QUARTER_TURN_Z,)),
    ('-4', 4, (ROTOREFLECTION_4,)),
    ('4/m', 8, (QUARTER_TURN_Z, HORIZONTAL_MIRROR)),
    ('422', 8, (QUARTER_TURN_Z, HALF_TURN_X)),
    ('4mm', 8, (QUARTER_TURN_Z, VERTICAL_MIRROR)),
    ('-42m', 8, (ROTOREFLECTION_4, HALF_TURN_X)),
    ('4/mmm', 16, (QUARTER_TURN_Z, HALF_TURN_X, HORIZONTAL_MIRROR)),
    ('3', 3, (THIRD_TURN_Z,)),
    ('-3', 6, (THIRD_TURN_Z, INVERSION)),
    ('32', 6, (THIRD_TURN_Z, HEX_HALF_TURN_X)),
    ('3m', 6, (THIRD_TURN_Z, HEX_VERTICAL_MIRROR)),
    ('-3m', 12, (THIRD_TURN_Z, HEX_HALF_TURN_X, INVERSION)),
    ('6', 6, (SIXTH_TURN_Z,)),
    ('-6', 6, (THIRD_TURN_Z, HORIZONTAL_MIRROR)),
    ('6/m', 12, (SIXTH_TURN_Z, HORIZONTAL_MIRROR)),
    ('622', 12, (SIXTH_TURN_Z, HEX_HALF_TURN_X)),
    ('6mm', 12, (SIXTH_TURN_Z, HEX_VERTICAL_MIRROR)),
    ('-6m2', 12, (THIRD_TURN_Z, HEX_HALF_TURN_X, HORIZONTAL_MIRROR)),
    ('6/mmm', 24, (SIXTH_TURN_Z, HEX_HALF_TURN_X, HORIZONTAL_MIRROR)),
    ('23', 12, (AXIS_CYCLE, HALF_TURN_X)),
    ('m-3', 24, (AXIS_CYCLE, HALF_TURN_X, INVERSION)),
    ('432', 24, (AXIS_CYCLE, QUARTER_TURN_Z)),
    ('-43m', 24, (AXIS_CYCLE, HALF_TURN_X, SWAP_XY)),
    ('m-3m', 48, (AXIS_CYCLE, QUARTER_TURN_Z, INVERSION)),
)


def _index(index):
    if type(index) is not int or not 1 <= index <= 32:
        raise ValueError('point-group index must be an integer in 1..32')
    return index - 1


def generators(index):
    """Immutable exact geometric generators in the stated lattice basis."""
    return CATALOGUE[_index(index)][2]


@lru_cache(None)
def matrices(index):
    """Generate the entire finite matrix group independently of GAP/CrystCat."""
    _, order, gs = CATALOGUE[_index(index)]
    found, pending = {IDENTITY}, [IDENTITY]
    while pending:
        a = pending.pop()
        for b in gs:
            c = _mul(a, b)
            if c not in found:
                found.add(c)
                if len(found) > order:
                    raise ArithmeticError('explicit geometric generators exceed their stated group order')
                pending.append(c)
    if len(found) != order:
        raise ArithmeticError('explicit geometric generators have the wrong order')
    return tuple(sorted(found))


@lru_cache(None)
def _spectrum(index):
    counts = Counter()
    group = matrices(index)
    for a in group:
        power, exponent = a, 1
        while power != IDENTITY:
            power = _mul(power, a)
            exponent += 1
            if exponent > len(group):
                raise ArithmeticError('invalid finite geometric element')
        counts[(exponent, sum(a[i][i] for i in range(3)), _det(a))] += 1
    return tuple(sorted(counts.items()))


def expected_spectrum(index):
    """Return [[order, trace, determinant], multiplicity] for the named type.

    This is invariant under a change of lattice basis and under a rigid change
    of spatial axes. Return a fresh mutable JSON-compatible value each time.
    """
    return [[list(key), count] for key, count in _spectrum(index)]
