"""Emit straight-line GAP from the already validated generic O5 scalar graph.

This does not rederive or simplify the formula. Every scalar instruction,
checked exact quotient, and signed floor/bit operation retains its semantics.
Field callbacks are normalized by the AFSPipO5 adapter before this runner.
"""
from pathlib import Path
import hashlib
import json

ROOT = Path(__file__).resolve().parents[1]


def compile_gap(program, digest):
    lines = [
        '# Generated by scripts/compile_pip_o5_straight.py; do not edit.',
        '# Exact straight-line execution of the existing complete scalar graph.',
        'AFSPipO5GeneralSourceSha256 := "{}";;'.format(digest),
        'AFSPipO5GeneralOperationCount := {};;'.format(len(program['program'])),
        'AFSPipO5GeneralCalls := 0;;',
        'AFSPipO5GeneralProgram := function(f,t)',
        'local v;v:=[];',
        'AFSPipO5GeneralCalls:=AFSPipO5GeneralCalls+1;',
    ]
    for index, item in enumerate(program['program'], 1):
        op, *args = item
        if op == 'const':
            rhs = str(args[0])
        elif op == 'field':
            name, face = args
            rhs = 'f.{}({})'.format(name, ','.join(
                't[{}][{}]'.format(a + 1, b + 1) for a, b in zip(face, face[1:])))
        elif op in ('add', 'mul'):
            rhs = 'v[{}]{}v[{}]'.format(args[0] + 1, '+' if op == 'add' else '*', args[1] + 1)
        elif op == 'mod':
            rhs = 'v[{}] mod {}'.format(args[0] + 1, args[1])
        elif op == 'div':
            value = 'v[{}]'.format(args[0] + 1)
            lines.append('if {} mod {}<>0 then Error("Invalid lower-tower integral quotient in pip O5");fi;'.format(value, args[1]))
            rhs = 'QuoInt({},{})'.format(value, args[1])
        elif op in ('floor', 'bit'):
            value = 'v[{}]'.format(args[0] + 1)
            divisor = args[1] if op == 'floor' else 2 ** args[1]
            rhs = 'QuoInt({}-({} mod {}),{})'.format(value, value, divisor, divisor)
            if op == 'bit':
                rhs += ' mod 2'
        else:
            raise ValueError('Unknown scalar instruction: {}'.format(op))
        lines.append('v[{}]:={};'.format(index, rhs))
    lines.append('return v[{}]/{};end;;'.format(program['output'] + 1, program['denominator']))
    return '\n'.join(lines) + '\n'


def main():
    source = ROOT / 'gap/pip_o5_program.json'
    raw = source.read_bytes()
    program = json.loads(raw)
    if program['denominator'] != 16 or not program['omega_zero']:
        raise ValueError('Expected the existing omega=0 numerator-mod-16 graph')
    target = ROOT / 'gap/pip_o5_general.g'
    target.write_text(compile_gap(program, hashlib.sha256(raw).hexdigest()))
    print('Emitted {} unchanged instructions to {}'.format(len(program['program']), target))


if __name__ == '__main__':
    main()
