#!/usr/bin/env python3
"""Check the current structured-expression census and its exact source scopes.

This checks occurrence arithmetic and the explicit phase-map expansion.
It does not collect cochains or prove their physical normalization.
"""
from pathlib import Path
import argparse
import collections
import hashlib
import importlib.util
import json
import re

HERE = Path(__file__).resolve().parent
DOCS = HERE.parent
ROOT = DOCS.parents[1]
EQUATIONS = DOCS / 'source/equations'
LEDGER = HERE / 'STRUCTURED_TERM_COUNTS.json'


def digest(data):
    return hashlib.sha256(data).hexdigest()


def refresh_reader_hashes(ledger):
    spec = importlib.util.spec_from_file_location('formula_builder', DOCS / 'build_reference.py')
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    catalog = json.loads((DOCS / 'source/catalog.json').read_text())
    entries = {entry['output']: entry for entry in catalog['pages']}
    for field in ('reader_hashes', 'supporting_reader_hashes'):
        for path in ledger[field]:
            source = entries[path]['source']
            rendered = ('<!-- Generated by build_reference.py; edit source/' + source
                        + ' instead. -->\n\n' + builder.render_source(source, {}))
            ledger[field][path] = digest(rendered.encode())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--refresh-reader-hashes', action='store_true',
                        help='Refresh page hashes after prose changes; counted source hashes stay fixed.')
    args = parser.parse_args()
    ledger = json.loads(LEDGER.read_text())
    if args.refresh_reader_hashes:
        refresh_reader_hashes(ledger)
        LEDGER.write_text(json.dumps(ledger, indent=2) + '\n')
    for path, expected in ledger['counted_source_hashes'].items():
        assert digest((ROOT / path).read_bytes()) == expected, path
    totals = collections.defaultdict(int)
    records = {}
    for record in ledger['records']:
        assert sum(record['terms_by_coefficient'].values()) == record['total'], record
        totals[record['dimension'] + ' ' + record['law']] += record['total']
        records[record['dimension'], record['law'], record['origin']] = record
    assert dict(totals) == ledger['totals'], (dict(totals), ledger['totals'])

    # The fixed map's finite word list and explicit terms establish 45+1.
    phase_page = (DOCS / 'source/pages/FOUR_DIMENSIONAL_MAJORANA_PHASE.md').read_text()
    words = re.search(r'```text\n(.*?)\n```', phase_page, re.S).group(1).split()
    assert len(words) == len(set(words)) == 32
    phase = (EQUATIONS / 'four-dimensional-majorana-phase--phase-change--1.tex').read_text()
    assert len(re.findall(r'\\nolimits_\{\d+\}', phase)) == 10
    assert all(term in phase for term in (r'\check n_3\cup_2', r's_1n_4', r'\check n_3\cup_1\overline{\beta\omega_2}'))
    assert r'\frac14\check n_3\cup_1\check n_3' in phase
    assert 32 + 10 + 3 == 45
    zero_half, zero_quarter = 44, 1
    general = {
        'gamma': ('four-dimensional--majorana-decoration--33.tex', 3),
        'gammapsi': ('four-dimensional--majorana-and-p-ip-decoration--36.tex', 3),
        'psi': ('four-dimensional--p-ip-decoration--37.tex', 1),
    }
    for origin, (filename, expected_calls) in general.items():
        text = (EQUATIONS / filename).read_text()
        calls = text.count('R_5[')
        assert calls == expected_calls, filename
        assert r'-s_1\mathcal{ℰ}_4^' in text, filename
        expected = (zero_half + zero_quarter) * calls + 1
        assert records['4+1D', 'E5', origin]['phase_transport_occurrences']['total'] == expected
    diagonal = {
        'gamma': ('four-dimensional-self-stacking--majorana-decoration--10.tex', 0, 2),
        'gammapsi': ('four-dimensional-self-stacking--majorana-and-p-ip-decoration--11.tex', 0, 1),
        'psi': ('four-dimensional-self-stacking--p-ip-decoration--12.tex', 1, 1),
    }
    for origin, (filename, expected_calls, other) in diagonal.items():
        text = (EQUATIONS / filename).read_text()
        calls = text.count('R_5[')
        assert calls == expected_calls, filename
        assert r'-s_1\mathcal{ℰ}_4^' in text, filename
        assert ledger['current_majorana_phase_transport']['self_additional_by_origin'][origin] == 45 * calls + other
    relative = json.loads((DOCS / 'data/four_dimensional_majorana_relative_words.json').read_text())
    assert relative['term_count'] == len(relative['terms']) == 1897
    X6 = (EQUATIONS / 'four-dimensional-majorana-phase--intrinsic--1.tex').read_text()
    assert len(re.findall(r'\\nolimits_\{\d+\}', X6)) == 4 and r'\cup_2' in X6
    X5 = (EQUATIONS / 'majorana-and-endpoints--majorana-contribution--24.tex').read_text()
    assert len(re.findall(r'\\nolimits_\{\d+\}', X5)) == 4
    assert records['3+1D', 'O5', 'gamma']['total'] == 15
    gamma = records['4+1D', 'E5', 'gamma']
    assert gamma['total_outer'] - 4 + sum(gamma['protected_lift_interior_counts']) == gamma['total']
    terminal = ledger['self_stacking']['terminal']['4+1D_full']
    assert sum(terminal['origins_outer']) == terminal['total_outer'] == 4407636
    assert terminal['total_outer'] - 4 + sum(terminal['gamma_lift_interiors']) == terminal['total_with_gamma_lift_wrappers_replaced']
    print(json.dumps({'status': 'PASS', 'metric': 'uncollected displayed occurrences',
                      'O6': totals['4+1D O6'], 'E5': totals['4+1D E5'],
                      'E5_self_outer': terminal['total_outer'],
                      'three_dimensional_O5_gamma': 15}, indent=2))


if __name__ == '__main__':
    main()
